name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build and test
        run: mvnw verify

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-rest-jar
          path: target/*.jar
